### ISSUE TITLE
What is your icon theme?

### ISSUE THREAD

**Issue by 05storm26** [MuhammedTaha02/MuhammedTaha02#1]
Hi,

Sorry for bothering but I have been following this github thread: https://github.com/micheleg/dash-to-dock/pull/1402#issuecomment-819147766. There is a picture there about your gnome dock. This: 

![picture about gnome dock](https://user-images.githubusercontent.com/62564400/114639002-8186e300-9cd5-11eb-931c-4338a23f4ca4.png)

Could you please tell me which icon theme this is?

**Comment by 05storm26** [comment]
@MuhammedTaha02

**Comment by MuhammedTaha02** [comment]
> @MuhammedTaha02

![image](https://user-images.githubusercontent.com/62564400/114830558-fdb42000-9dd4-11eb-8eba-64e7aa79e35c.png)

My theme settings are like this @05storm26 :)

**Comment by 05storm26** [comment]
Thanks!

**Comment by MuhammedTaha02** [comment]
> Thanks!

You're welcome :)
